// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/motionsensor/server.proto

package motion_sensor

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Position int32

const (
	Position_POSITION_UNSPECIFIED Position = 0
	Position_DOOR                 Position = 1
	Position_DESK                 Position = 2
)

var Position_name = map[int32]string{
	0: "POSITION_UNSPECIFIED",
	1: "DOOR",
	2: "DESK",
}

var Position_value = map[string]int32{
	"POSITION_UNSPECIFIED": 0,
	"DOOR":                 1,
	"DESK":                 2,
}

func (x Position) String() string {
	return proto.EnumName(Position_name, int32(x))
}

func (Position) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_4f022a59b1cb2c8d, []int{0}
}

type DetectMovementRequest struct {
	Position             Position `protobuf:"varint,1,opt,name=position,proto3,enum=nicofeals.hommy.motion_sensor.Position" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetectMovementRequest) Reset()         { *m = DetectMovementRequest{} }
func (m *DetectMovementRequest) String() string { return proto.CompactTextString(m) }
func (*DetectMovementRequest) ProtoMessage()    {}
func (*DetectMovementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f022a59b1cb2c8d, []int{0}
}

func (m *DetectMovementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectMovementRequest.Unmarshal(m, b)
}
func (m *DetectMovementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectMovementRequest.Marshal(b, m, deterministic)
}
func (m *DetectMovementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectMovementRequest.Merge(m, src)
}
func (m *DetectMovementRequest) XXX_Size() int {
	return xxx_messageInfo_DetectMovementRequest.Size(m)
}
func (m *DetectMovementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectMovementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DetectMovementRequest proto.InternalMessageInfo

func (m *DetectMovementRequest) GetPosition() Position {
	if m != nil {
		return m.Position
	}
	return Position_POSITION_UNSPECIFIED
}

type DetectMovementResponse struct {
	Position             Position `protobuf:"varint,1,opt,name=position,proto3,enum=nicofeals.hommy.motion_sensor.Position" json:"position,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DetectMovementResponse) Reset()         { *m = DetectMovementResponse{} }
func (m *DetectMovementResponse) String() string { return proto.CompactTextString(m) }
func (*DetectMovementResponse) ProtoMessage()    {}
func (*DetectMovementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4f022a59b1cb2c8d, []int{1}
}

func (m *DetectMovementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DetectMovementResponse.Unmarshal(m, b)
}
func (m *DetectMovementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DetectMovementResponse.Marshal(b, m, deterministic)
}
func (m *DetectMovementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DetectMovementResponse.Merge(m, src)
}
func (m *DetectMovementResponse) XXX_Size() int {
	return xxx_messageInfo_DetectMovementResponse.Size(m)
}
func (m *DetectMovementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DetectMovementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DetectMovementResponse proto.InternalMessageInfo

func (m *DetectMovementResponse) GetPosition() Position {
	if m != nil {
		return m.Position
	}
	return Position_POSITION_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("nicofeals.hommy.motion_sensor.Position", Position_name, Position_value)
	proto.RegisterType((*DetectMovementRequest)(nil), "nicofeals.hommy.motion_sensor.DetectMovementRequest")
	proto.RegisterType((*DetectMovementResponse)(nil), "nicofeals.hommy.motion_sensor.DetectMovementResponse")
}

func init() { proto.RegisterFile("rpc/motionsensor/server.proto", fileDescriptor_4f022a59b1cb2c8d) }

var fileDescriptor_4f022a59b1cb2c8d = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2d, 0x2a, 0x48, 0xd6,
	0xcf, 0xcd, 0x2f, 0xc9, 0xcc, 0xcf, 0x2b, 0x4e, 0xcd, 0x2b, 0xce, 0x2f, 0xd2, 0x2f, 0x4e, 0x2d,
	0x2a, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x92, 0xcd, 0xcb, 0x4c, 0xce, 0x4f,
	0x4b, 0x4d, 0xcc, 0x29, 0xd6, 0xcb, 0xc8, 0xcf, 0xcd, 0xad, 0xd4, 0x83, 0x28, 0x8d, 0x87, 0xa8,
	0x55, 0x8a, 0xe1, 0x12, 0x75, 0x49, 0x2d, 0x49, 0x4d, 0x2e, 0xf1, 0xcd, 0x2f, 0x4b, 0xcd, 0x4d,
	0xcd, 0x2b, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x72, 0xe6, 0xe2, 0x28, 0xc8, 0x2f,
	0xce, 0x04, 0xa9, 0x95, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x33, 0x52, 0xd7, 0xc3, 0x6b, 0x94, 0x5e,
	0x00, 0x54, 0x79, 0x10, 0x5c, 0xa3, 0x52, 0x2c, 0x97, 0x18, 0xba, 0xe9, 0xc5, 0x05, 0x20, 0x77,
	0x52, 0xc5, 0x78, 0x2d, 0x0b, 0x2e, 0x0e, 0x98, 0xa8, 0x90, 0x04, 0x97, 0x48, 0x80, 0x7f, 0xb0,
	0x67, 0x88, 0xa7, 0xbf, 0x5f, 0x7c, 0xa8, 0x5f, 0x70, 0x80, 0xab, 0xb3, 0xa7, 0x9b, 0xa7, 0xab,
	0x8b, 0x00, 0x83, 0x10, 0x07, 0x17, 0x8b, 0x8b, 0xbf, 0x7f, 0x90, 0x00, 0x23, 0x98, 0xe5, 0x1a,
	0xec, 0x2d, 0xc0, 0x64, 0xd4, 0xcb, 0xc8, 0xc5, 0xe3, 0x0b, 0x36, 0x3e, 0x18, 0x6c, 0xba, 0x50,
	0x2d, 0x17, 0x1f, 0xaa, 0x4b, 0x85, 0x4c, 0x08, 0xb8, 0x07, 0x6b, 0xb0, 0x49, 0x99, 0x92, 0xa8,
	0x0b, 0x12, 0x1c, 0x4e, 0xfc, 0x51, 0xbc, 0x28, 0xea, 0x92, 0xd8, 0xc0, 0xb1, 0x67, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0xcc, 0x81, 0xa4, 0xe0, 0xde, 0x01, 0x00, 0x00,
}
